### ISSUE TITLE
No se puede modificar el estilo del nav de la app

### ISSUE THREAD

**Issue by Franconeri85** [fedemiguez/sejuega-app#6]
@catrielmuller Profe, estamos acá que no podemos cambiar ningun estilo de la app y no sabemos porque. Intentamos cambiarlo desde el style.css y de ionic.scss. Ningun cambio lo reconoce.
![21321](https://cloud.githubusercontent.com/assets/13700501/14622698/54837d48-05a2-11e6-9273-dc536d8db34f.PNG)

**Comment by catrielmuller** [comment]
Editando el archivo www/css/style.css se modificaron los estilo. no se que usuario puedo usar para entrar a la app. Pero editando ese archivo si se modifican los estilos.
