### ISSUE TITLE
No nos llega el id del usuario

### ISSUE THREAD

**Issue by fedemiguez** [fedemiguez/sejuega-app#7]
Hola, @catrielmuller necesitamos traer el id del usuario para poder ponerlo en una url, porque con esa url eliminamos de la lista el mismo usuario. En la api funciona perfecto pero en la aplicacion no estaria funcionando y seguro es por algo de la sintaxis de angular porque me devuelve en la consola "indefinido" aca va el pedazo de codigo.

.controller('invitarCtrl', function($scope, $http, $location, $rootScope, $stateParams, $ionicPopup) {

```
console.log($rootScope.userToken);     

$scope.user = [];

$http.get('http://sejuega.herokuapp.com/me', {headers: {'auth-token': $rootScope.userToken}}).then(function(resp) {
  $scope.user.id = resp.data.data;
  console.log('Succes', resp.data.data);
}, function(err) {
  console.error('ERR', err);
  $location.path('/app/entrar');
  // err.status will contain the status code
});
```

  $scope.usuarioList = [];
   $scope.$on('$ionicView.beforeEnter', function() {
    $http.get('http://sejuega.herokuapp.com/jugadores/'+$scope.user.id).then(function(resp) {
      $scope.usuarioList = resp.data.data;
      console.log('Succes', resp.data.data);
    }, function(err) {
      console.error('ERR', err);
      // err.status will contain the status code
    });
  });

```
    $scope.selected = {
    id_u: []
    };




  $scope.doInvitar = function() {
  $http.post('http://sejuega.herokuapp.com/partidos/'+ $stateParams.partidoId+'/invitar', $scope.selected , {headers: {'auth-token': $rootScope.userToken}}).then(function(resp) {
    console.log(resp.data);

 var alertPopup = $ionicPopup.alert({
         title: 'Invitado con Exito!',
         template: 'Segui invitando jugadores'
       });
       alertPopup.then(function(res) {
         $location.path('/app/invitar/'+$stateParams.partidoId);
       });

}, function(err) {
  console.error('ERR', err);

  // err.status will contain the status code
});
};
```

**Comment by catrielmuller** [comment]
No entiendo cual de los tres llamados es el que tenes inconvenientes.

**Comment by fedemiguez** [comment]
en este $http.get('http://sejuega.herokuapp.com/jugadores/'+$scope.user.id).then(function(resp) 

no me trae el id del usuario para poder identificarlo y mandar esa ruta a la api

**Comment by catrielmuller** [comment]
Fede no puedo testear el codigo por que no tienen actualizado el repositorio con el codigo que me comentas.

Por lo que puedo ver, el error es por que estan intentando llamar a "http://sejuega.herokuapp.com/jugadores/" al mismo tiempo que llaman a "http://sejuega.herokuapp.com/me" por lo que esta ultima no termina de completarse y a '/jugadores' no tienen disponible el user.id que obtienen de "/me"

Deberian hacer algo como esto:

``` javascript
$scope.getUsuarioList = function(){
    $http.get('http://sejuega.herokuapp.com/jugadores/'+$scope.user.id).then(function(resp) {
        $scope.usuarioList = resp.data.data;
        console.log('Succes', resp.data.data);
    }, function(err) {
        console.error('ERR', err);
    }); 
}

$http.get('http://sejuega.herokuapp.com/me', {headers: {'auth-token': $rootScope.userToken}}).then(function(resp) {
  $scope.user.id = resp.data.data;
  $scope.getUsuarioList();
  console.log('Succes', resp.data.data);
}, function(err) {
  console.error('ERR', err);
  $location.path('/app/entrar');
  // err.status will contain the status code
});
```

Primero definen una función que hace ajax a '/jugadores' y la ejecutan cuando termina el '/me' y ya tienen definido el user.id

**Comment by fedemiguez** [comment]
profe ahi actualice el repositorio, porque no funciona lo que me pasaste sigue sin desaparecer el usuario y cuando remplazo en el codigo el scope por el numero de id si desaparece

**Comment by fedemiguez** [comment]
cuando se envia se envia la ruta asi : http://sejuega.herokuapp.com/jugadores/[object%20Object]
![image](https://cloud.githubusercontent.com/assets/13700491/15459557/c0aa22b6-207c-11e6-9fe5-417206bda001.png)

**Comment by catrielmuller** [comment]
@fedemiguez podrías pasarme por email un usuario y contraseña de esto para probarlo.

**Comment by fedemiguez** [comment]
fedeemiguez@gmail.com y la contraseña es fede12345

**Comment by catrielmuller** [comment]
app.js linea 618 cambiar:
$scope.user.id = resp.data.data;
por
$scope.user = resp.data.data;
