### ISSUE TITLE
En localhost funciona bien, pero en el movil no nos deja iniciar sesión

### ISSUE THREAD

**Issue by Franconeri85** [fedemiguez/sejuega-app#9]
@catrielmuller  Hola profe, estamos con un problema con los chicos. De un dia para el otro, en el celular, no nos deja acceder, nos tira que la contraseña es incorrecta, pero desde la pc, entra bien. Usted sabe a que se debe? 
![captura](https://cloud.githubusercontent.com/assets/13700501/16600065/c95823be-42db-11e6-9ef2-df46adb520c5.PNG) 
![42816977-3150-4f75-a5a9-e8d2376ec952](https://cloud.githubusercontent.com/assets/13700501/16600074/d48f8b00-42db-11e6-8ec1-1eee5f655575.jpg)

**Comment by catrielmuller** [comment]
Deberían usar el Developer Tools de Google Chrome para ver los llamados http si como los esta enviando si es al lugar correcto y verificar si así los espera la API.

https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

**Comment by fedemiguez** [comment]
personalmente en mi celular no me funciona developer tools, conecto mi celu a la pc y no me aparece, tiene android 4.3. Instale los drivers es un alcate idol 2 mini. Habria otra herramienta para usar?

**Comment by fedemiguez** [comment]
hola @catrielmuller , pudimos usar el developer tools y encontramos que no se esta pudiendo mandar, la solicitud a la api, a diferencia de cuando lo probamos de la compu.

smartphone:
![image](https://cloud.githubusercontent.com/assets/13700491/16639144/200ac166-43c3-11e6-9b9c-8aabf13c345b.png)

pc:

![image](https://cloud.githubusercontent.com/assets/13700491/16639166/63bc010e-43c3-11e6-9a41-84c894dda55b.png)

nose si sera el tema de algunos permisos o que porque, no modificamos nada en el codigo y antes funcionaba.

en la pc se manda primero como un option y despues como post:
![image](https://cloud.githubusercontent.com/assets/13700491/16639222/e580c56c-43c3-11e6-872f-3930de4531ce.png)

en el smartphone se manda como un post directamente:
![image](https://cloud.githubusercontent.com/assets/13700491/16639225/f39c693a-43c3-11e6-8b21-bbf1a37975d7.png)

**Comment by fedemiguez** [comment]
ya lo solucionamos, de alguna manera se habia borrado el plugin de whitelist lo volvimos a agregar y funciona
